# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "HAN PENG"
email: penghan1992@gmail.com
name: "Han Peng"
repository: "ha-ha-ha-han/ha-ha-ha-han.github.io"
analytics:
  provider: "google"
  google:
    tracking_id: UA-113926594-1
author:
  name   : "Han Peng"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a DPhil student in Physics Department, University of Oxford. <br>
My research interest lies in the electronic structure of functional materials such as graphene based heterostructures.  Another topic I am excited about is to apply advanced data analysis methods to discover the underlying patterns from the voluminous modern scientific data. "
  email  : "penghan1992@gmail.com"
  uri    : "https://ha-ha-ha-han.github.io/"
  home   : # null (default), "absolute or relative url to link to author home"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ha-ha-ha-han.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-remote-theme
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise" "default"
  
remote_theme: "mmistakes/minimal-mistakes"

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-43851426-1"

#theme: minimal-mistakes-jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
